# -*- coding: utf-8 -*-
"""exemplo1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/148d0RCq4gJ3CZlfMNWCJwBB9t1EuxNni
"""

import streamlit as st
from json import loads
from pandas import read_csv
st.markdown('''
# Exibidor de arquivos

## Suba um arquivo e vejamos o que acontece :smile :heart
''')

arquivo = st.file_uploader(
    'Suba seu arquivo aqui!',
    type = ['jpg', 'png', 'py', 'csv', 'json', 'wav']
)
if arquivo:
  print(arquivo.type)
  match arquivo.type.split('/'):
    case 'application', 'json':
      st.json(loads(arquivo.read()))
    case 'image', _:
      st.image(arquivo)
    case 'text', 'x-python':
      st.code(arquivo.read().decode())
    case 'text', 'csv':
      df = read_csv(arquivo)
      st.dataframe(df)
      st.bar_chart(df)
    case 'audio', _:
      st.audio(arquivo)
else: st.error("Ainda não há nenhum arquivo")