# -*- coding: utf-8 -*-
"""questionario_streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PXPnTo2HA6G1emuzzYjqqtjcuIUYdfIy
"""

import streamlit as st
import matplotlib.pyplot as plt

# Função para gerar pergunta e obter resposta
def perguntar(pergunta, opcoes):
    st.header(pergunta)
    resposta = st.radio(f"Escolha uma das 5 opções:", opcoes, key=pergunta)
    return resposta

# Função para criar os gráficos
def make_graph(domains, facet_results, labels):
    # Separate the facets by their respective domains
    domain_facets = {
        'Abertura': ['O1', 'O3', 'O5'],
        'Conscienciosidade': ['C1', 'C2', 'C4', 'C5'],
        'Extroversão': ['E1', 'E2', 'E3', 'E4'],
        'Afabilidade': ['A1', 'A3', 'A4'],
        'Neuroticismo': ['N1', 'N2', 'N3', 'N5']
    }

    for domain in domains:  # Abertura, Conscienciosidade, (...)
        facets = domain_facets[domain]  # domain_facets[Abertura] -> ['O1', 'O3', 'O5']

        # Get the scores for the current facets
        answered_scores = [facet_results[facet] for facet in facets]

        facet_labels = labels[domain]

        print(f"\n\n\n\n======={domain}=======\n")
        for facet_label, answered_score in zip(facet_labels, answered_scores):
            print(f"{facet_label}: {answered_score}")
        print(f"\n")

        # Plot the bar chart for the current domain
        plt.bar(facet_labels, answered_scores)
        plt.xticks(rotation=45, ha='right')
        plt.ylim(0, 25)  # Adjust this limit according to your needs
        plt.title(domain)

        # Show the plot
        plt.show()



# Título
st.title('SOFT K 4.0 - Questionário')
st.write('Legenda das alternativas: a = Muito impreciso, b = Moderadamente impreciso, c = Neutro, d = Moderadamente preciso, e = Muito preciso')
# Perguntas e opções de resposta
custom_values = {
    "Q01 - Me preocupo com as coisas.": ["a", "b", "c", "d", "e"],
    "Q02 - Receio sobre o que há de ruim que possa acontecer.": ["a", "b", "c", "d", "e"],
    "Q03 - Fico estressado facilmente.": ["a", "b", "c", "d", "e"],
    "Q04 - Facilmente fico irritado.": ["a", "b", "c", "d", "e"],
    "Q05 - Perco minha calma.": ["a", "b", "c", "d", "e"],
    "Q06 - Raramente me sinto revoltado.": ["a", "b", "c", "d", "e"],
    "Q07 - Frequentemente me sinto cabisbaixo.": ["a", "b", "c", "d", "e"],
    "Q08 - Não gosto de mim mesmo.": ["a", "b", "c", "d", "e"],
    "Q09 - Constantemente me sinto deprimido.": ["a", "b", "c", "d", "e"],
    "Q10 - Minhas opiniões voltadas para mim mesmo são desfavoráveis.": ["a", "b", "c", "d", "e"],
    "Q11 - Normalmente como muito.": ["a", "b", "c", "d", "e"],
    "Q12 - Sacio minhas vontades aos montes.": ["a", "b", "c", "d", "e"],
    "Q13 - Raramente passo do limite.": ["a", "b", "c", "d", "e"],
    "Q14 - Consigo manter controle sobre minhas compulsões.": ["a", "b", "c", "d", "e"],
    "Q15 - Faço amizades facilmente.": ["a", "b", "c", "d", "e"],
    "Q16 - Interajo calorosamente com pessoas.": ["a", "b", "c", "d", "e"],
    "Q17 - Me sinto na minha zona de conforto por mais que eu esteja perto de pessoas.": ["a", "b", "c", "d", "e"],
    "Q18 - Ajo com tranquilidade ao interagir com os outros.": ["a", "b", "c", "d", "e"],
    "Q19 - Adoro festas grandes.": ["a", "b", "c", "d", "e"],
    "Q20 - Converso com muitas pessoas diferentes durante festas.": ["a", "b", "c", "d", "e"],
    "Q21 - Não gosto de eventos lotados.": ["a", "b", "c", "d", "e"],
    "Q22 - Evito multidões.": ["a", "b", "c", "d", "e"],
    "Q23 - Assumo comando.": ["a", "b", "c", "d", "e"],
    "Q24 - Induzo-me a conduzir pessoas.": ["a", "b", "c", "d", "e"],
    "Q25 - Assumo controle das coisas.": ["a", "b", "c", "d", "e"],
    "Q26 - Aguardo a orientação de outros.": ["a", "b", "c", "d", "e"],
    "Q27 - Estou sempre ocupado.": ["a", "b", "c", "d", "e"],
    "Q28 - Estou sempre transitando de uma coisa pra outra, de um lugar pra outro.": ["a", "b", "c", "d", "e"],
    "Q29 - Faço muita coisa no meu tempo livre.": ["a", "b", "c", "d", "e"],
    "Q30 - Gerencio muitas coisas ao mesmo tempo.": ["a", "b", "c", "d", "e"],
    "Q31 - Tenho imaginação vívida.": ["a", "b", "c", "d", "e"],
    "Q32 - Curto ir longe com a mente fantasiosamente.": ["a", "b", "c", "d", "e"],
    "Q33 - Gosto passar o dia divagando, sonhar-acordado.": ["a", "b", "c", "d", "e"],
    "Q34 - Gosto de me perder em meio aos pensamentos.": ["a", "b", "c", "d", "e"],
    "Q35 - Experiencio minhas emoções intensamente.": ["a", "b", "c", "d", "e"],
    "Q36 - Raramente fico sentimental.": ["a", "b", "c", "d", "e"],
    "Q37 - Meu comportamento não é facilmente afetado pelas minhas emoções.": ["a", "b", "c", "d", "e"],
    "Q38 - Emocionalmente passo por poucos altos e baixos.": ["a", "b", "c", "d", "e"],
    "Q39 - Não sou interessado em ideias abstratas.": ["a", "b", "c", "d", "e"],
    "Q40 - Espontaneamente evito discussões filosóficas.": ["a", "b", "c", "d", "e"],
    "Q41 - Tenho dificuldade em compreender ideias abstratas.": ["a", "b", "c", "d", "e"],
    "Q42 - Não tenho interesse em discussões teóricas.": ["a", "b", "c", "d", "e"],
    "Q43 - Confio nos outros.": ["a", "b", "c", "d", "e"],
    "Q44 - Tenho fé na boa intenção dos outros.": ["a", "b", "c", "d", "e"],
    "Q45 - Acredito no que as pessoas dizem.": ["a", "b", "c", "d", "e"],
    "Q46 - Sou receoso com as pessoas.": ["a", "b", "c", "d", "e"],
    "Q47 - Me atento aos cuidados com os outros.": ["a", "b", "c", "d", "e"],
    "Q48 - Adoro ajudar os outros.": ["a", "b", "c", "d", "e"],
    "Q49 - Sou indiferente com os sentimentos dos outros.": ["a", "b", "c", "d", "e"],
    "Q50 - Não tenho tempo para os outros.": ["a", "b", "c", "d", "e"],
    "Q51 - Amo uma briga boa.": ["a", "b", "c", "d", "e"],
    "Q52 - Elevo o tom com as pessoas.": ["a", "b", "c", "d", "e"],
    "Q53 - Insulto pessoas.": ["a", "b", "c", "d", "e"],
    "Q54 - Dou o troco nos outros.": ["a", "b", "c", "d", "e"],
    "Q55 - Concluo atividades com sucesso.": ["a", "b", "c", "d", "e"],
    "Q56 - Sobressaio no que eu faço.": ["a", "b", "c", "d", "e"],
    "Q57 - Lido com tarefas tranquilamente.": ["a", "b", "c", "d", "e"],
    "Q58 - Sei como lidar pra fazer as coisas acontecerem.": ["a", "b", "c", "d", "e"],
    "Q59 - Gosto da ordem (normas).": ["a", "b", "c", "d", "e"],
    "Q60 - Gosto de ajeitar as coisas.": ["a", "b", "c", "d", "e"],
    "Q61 - Deixo meu quarto bagunçado.": ["a", "b", "c", "d", "e"],
    "Q62 - Deixo largado minhas coisas.": ["a", "b", "c", "d", "e"],
    "Q63 - Trabalho duro.": ["a", "b", "c", "d", "e"],
    "Q64 - Faço mais do que os outros esperam de mim.": ["a", "b", "c", "d", "e"],
    "Q65 - Estabeleço critérios elevados para mim e para os outros.": ["a", "b", "c", "d", "e"],
    "Q66 - Não me sinto muito motivado a ter êxito.": ["a", "b", "c", "d", "e"],
    "Q67 - De imediato dou início aos afazeres.": ["a", "b", "c", "d", "e"],
    "Q68 - Vejo como trabalhoso agir de fato para pôr os afazeres em prática.": ["a", "b", "c", "d", "e"],
    "Q69 - Preciso ser impulsionado pra começar algo.": ["a", "b", "c", "d", "e"],
    "Q70 - Tenho dificuldade em iniciar tarefas.": ["a", "b", "c", "d", "e"]
}

# Inicializar um dicionário para armazenar as respostas
respostas = {}

# Loop para salvar as respostas
for pergunta, opcoes in custom_values.items():
    resposta = perguntar(pergunta, opcoes)
    st.write(f"Resposta: {resposta}")
    respostas[pergunta] = resposta

# Exibir a lista com as respostas
st.write(respostas)

# Mapear as respostas para pontuações (a = 1, b = 2, c = 3, d = 4, e = 5)
pontuacoes = {"a": 1, "b": 2, "c": 3, "d": 4, "e": 5}


# Calcular os escores para cada dimensão de personalidade
extroversao = (pontuacoes[respostas["Q15 - Faço amizades facilmente."]] +
               pontuacoes[respostas["Q16 - Interajo calorosamente com pessoas."]] +
               pontuacoes[respostas["Q17 - Me sinto na minha zona de conforto por mais que eu esteja perto de pessoas."]] +
               pontuacoes[respostas["Q18 - Ajo com tranquilidade ao interagir com os outros."]]) / 4

conscienciosidade = (pontuacoes[respostas["Q57 - Lido com tarefas tranquilamente."]] +
                     pontuacoes[respostas["Q58 - Sei como lidar pra fazer as coisas acontecerem."]] +
                     pontuacoes[respostas["Q59 - Gosto da ordem (normas)."]] +
                     pontuacoes[respostas["Q60 - Gosto de ajeitar as coisas."]]) / 4

neuroticismo = (pontuacoes[respostas["Q01 - Me preocupo com as coisas."]] +
               pontuacoes[respostas["Q02 - Receio sobre o que há de ruim que possa acontecer."]] +
               pontuacoes[respostas["Q03 - Fico estressado facilmente."]] +
               pontuacoes[respostas["Q04 - Facilmente fico irritado."]] +
               pontuacoes[respostas["Q05 - Perco minha calma."]] +
               pontuacoes[respostas["Q06 - Raramente me sinto revoltado."]] +
               pontuacoes[respostas["Q07 - Frequentemente me sinto cabisbaixo."]] +
               pontuacoes[respostas["Q08 - Não gosto de mim mesmo."]] +
               pontuacoes[respostas["Q09 - Constantemente me sinto deprimido."]] +
               pontuacoes[respostas["Q10 - Minhas opiniões voltadas para mim mesmo são desfavoráveis."]]) / 10

afabilidade = (pontuacoes[respostas["Q43 - Confio nos outros."]] +
               pontuacoes[respostas["Q44 - Tenho fé na boa intenção dos outros."]] +
               pontuacoes[respostas["Q45 - Acredito no que as pessoas dizem."]] +
               pontuacoes[respostas["Q46 - Sou receoso com as pessoas."]] +
               pontuacoes[respostas["Q47 - Me atento aos cuidados com os outros."]] +
               pontuacoes[respostas["Q48 - Adoro ajudar os outros."]]) / 6

abertura = (pontuacoes[respostas["Q31 - Tenho imaginação vívida."]] +
            pontuacoes[respostas["Q32 - Curto ir longe com a mente fantasiosamente."]] +
            pontuacoes[respostas["Q33 - Gosto passar o dia divagando, sonhar-acordado."]] +
            pontuacoes[respostas["Q34 - Gosto de me perder em meio aos pensamentos."]]) / 4

# Criar gráfico de barras para cada dimensão de personalidade
st.header("Gráficos de Personalidade")
fig, ax = plt.subplots()
dimensoes = ["Extroversão", "Conscienciosidade", "Neuroticismo", "Afabilidade", "Abertura"]
escores = [extroversao, conscienciosidade, neuroticismo, afabilidade, abertura]
ax.barh(dimensoes, escores, color='skyblue')
ax.set_xlabel('Escore')
ax.set_title('Dimensões de Personalidade')
st.pyplot(fig)